### ISSUE TITLE
Functional Authentication!

### ISSUE THREAD

**Issue by rywarsaw** [rywarsaw/diy-java-api#1]
Hey guys!

Just a update for anyone watching this project, I have completed the new authentication functionality! Thanks to some help from @derekr and the Diy.org API documentation I was able to put together a very efficient and secure authentication function.

You can view the code here, 

https://gist.github.com/rywarsaw/585a4c4eb3c0232c31c4

A user can easily inject credentials into the method, and best of all? They don't stay around! After authentication the method closes thus not leaving data laying around. This is also very memory efficient and definitely alot faster than my original design.

I plan to have the complete API done very soon!

**Comment by derekr** [comment]
Awesome! :D

Just a heads up: the gist link isn't working.

**Comment by rywarsaw** [comment]
@derekr Thanks for the heads up, not sure what happened there. I'll try to fix it :P
