### ISSUE TITLE
Duplicate Challenge Difficulty responses in diy.org API

### ISSUE THREAD

**Issue by rywarsaw** [rywarsaw/diy-java-api#2]
When using API version 3.3.1 (Latest), querying the Challenge part of the Diy.org API. Difficulty is specified twice, both under Stats and Meta. Is this a bug @derekr ?

**Comment by derekr** [comment]
Word will look in to it.

**Comment by rywarsaw** [comment]
@derekr did you get a chance to look into this?

**Comment by jackaperkins** [comment]
@rywarsaw Good eye! They're using the same value from the database so either is correct. The Meta subobject is more future proof, at some point i'll probably phase out the stats object since it only has that one duplicate field.

**Comment by rywarsaw** [comment]
Thank you @jackaperkins I can finish the challenge API now :)

**Comment by rywarsaw** [comment]
This issue has been fixed.
