### ISSUE TITLE
HMAC Token Generation with SHA-1

### ISSUE THREAD

**Issue by rywarsaw** [rywarsaw/diy-java-api#4]
Why hasn't DIY switched over to a more secure SHA, such as SHA-256 or SHA-2? SHA-1 has been known to be decrypted and hackable. I would like to Implement HMAC Tokens into the API but I don't feel doing so is a good idea until there is a more secure form of SHA available for HMAC Token Generation. @derekr

**Comment by derekr** [comment]
Mostly for speed and legacy. It was implemented before my time, and nothing ever came up that warranted a change.

http://crypto.stackexchange.com/questions/15382/hmac-sha1-vs-hmac-sha256
